name: generate-snake

on:
  schedule:
    # 每 6 小时，执行一次
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
       # Step 2: Checkout the 'output' branch
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output

      # Step 3: Add, commit, and push the files to the 'output' branch
      - name: Commit and push generated files to 'output' branch
        run: |
          # Create dist folder if it doesn't exist
          mkdir -p dist
          
          # Add generated files
          git add dist/
          
          # Commit the changes
          git commit -m "Add generated snake files"
          
          # Push to the 'output' branch
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}