name: Metrics

on:
  # Schedule updates (each 8 hour)
  schedule: [{cron: "0 */8 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  generate_profile:
    runs-on: ubuntu-latest
    steps:
      - name: snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}